CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL,
    email   VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR NOT NULL,
    description     VARCHAR NOT NULL,
    is_available    BOOLEAN NOT NULL,
    owner_id        BIGINT  NOT NULL,
    CONSTRAINT fk_items_to_users FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date  TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date    TIMESTAMP WITH TIME ZONE NOT NULL,
    item_id     BIGINT                   NOT NULL,
    booker_id   BIGINT                   NOT NULL,
    status      VARCHAR                  NOT NULL,
    CONSTRAINT fk_bookings_to_items FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_bookings_to_users FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT status_check CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR                     NOT NULL,
    created     TIMESTAMP WITH TIME ZONE    NOT NULL,
    author_id   BIGINT                      NOT NULL,
    item_id     BIGINT                      NOT NULL,
    CONSTRAINT fk_comment_to_user FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_comment_to_item FOREIGN KEY (item_id) REFERENCES items (id)
);